#!/usr/bin/env bash
#
# build openM++ Python examples

# push into ompp root and make log directory if not exist

if [ ! -d ompp ]; then 

  echo mkdir ompp
  
  if ! mkdir ompp; then
    echo FAILED
    exit 1
  fi
fi

pushd ompp

if [ ! -d log ]; then mkdir log; fi

# log build environment 

echo Log file: log/build-python.log
echo `date` Build openM++ Python examples | tee log/build-python.log 

# get source code from git, if directory not already exist

if [ ! -d ompp-python ]; then
  
  echo git clone https://github.com/openmpp/python ompp-python | tee -a log/build-python.log
  
  if ! git clone https://github.com/openmpp/python ompp-python >> log/build-python.log 2>&1;
  then
    echo FAILED git clone | tee -a log/build-python.log
    exit 1
  fi
else
  echo Skip: git clone
fi

echo `date` Done. | tee -a log/build-python.log
popd
